#pragma once

#define VERSION_PREFIX "0.1"

#ifdef BUILD_SERVER_VERSION
#define STRINGIFY_HELPER(x) #x
#define VERSION_STRING(x) STRINGIFY_HELPER(x)
#define VERSION_SUFFIX VERSION_STRING(BUILD_SERVER_VERSION)
#else
#define DEBUG_VERSION "0debug"
#define VERSION_SUFFIX DEBUG_VERSION
#endif

#define VERSION std::string(VERSION_PREFIX) + "." + VERSION_SUFFIX
